name: CoT_4-shot_gemini-2.0-flash-lite-001

input_file: "D:/Git_repo/ViSoMMSD/data/interim/full_data/llm_input.json"
image_folder: "D:/Git_repo/ViSoMMSD/data/all/merged"

output_file: "D:/Git_repo/ViSoMMSD/data/external/llm_label/CoT_4-shot_gemini-2.0-flash-lite-001.json"
failed_file: "D:/Git_repo/ViSoMMSD/data/external/llm_label/failed_CoT_4-shot_gemini-2.0-lite-flash-001.json"

model_name: "gemini-2.0-flash-lite-001"
prompt_path: "D:/Git_repo/ViSoMMSD/prompt/CoT_4-shot.yaml"
#Gemini 2.0 flash-lite RPM = 4000

http_timeout: 30 #second [20-120]
#batch_size: 30 # RPM/60
max_workers: 100 # RPM/60*http_timeout*0.6


